version: '3.8'
services:
  db:
    image: postgres:14.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  mongo-db:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - db:/var/lib/mongo/data
volumes:
  db:
    driver: local
